fix: more CI failure caused by luarocks
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>

diff --git a/.github/workflows/fuzzing-ci.yaml b/.github/workflows/fuzzing-ci.yaml
--- a/.github/workflows/fuzzing-ci.yaml
+++ b/.github/workflows/fuzzing-ci.yaml
@@ -43,7 +43,13 @@ jobs:
         sudo apt-get install -y git openresty curl openresty-openssl111-dev unzip make gcc
         ./utils/linux-install-luarocks.sh
 
-        make deps
+        for (( i = 0; i < 10; i++ )); do
+            if [[ "$i" -eq 10 ]]; then
+                echo "failed to make deps in time"
+                exit 1
+            fi
+            make deps && break
+        done
         make init
         make run
 
