apply code suggestions from review

diff --git a/.github/workflows/source-install.yml b/.github/workflows/source-install.yml
--- a/.github/workflows/source-install.yml
+++ b/.github/workflows/source-install.yml
@@ -88,33 +88,33 @@ jobs:
 
       - name: Test apisix
         run: |
-            wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
-            get_admin_key() {
-                local admin_key=$(yq '.deployment.admin.admin_key[0].key' conf/config.yaml)
-                echo "$admin_key"
+          wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
+          get_admin_key() {
+              local admin_key=$(yq '.deployment.admin.admin_key[0].key' conf/config.yaml)
+              echo "$admin_key"
+          }
+          export admin_key=$(get_admin_key); echo $admin_key
+          cat conf/config.yaml
+          curl -v http://127.0.0.1:9180/apisix/admin/routes/1 \
+          -H "X-API-KEY: $admin_key" -X PUT -d '
+          {
+            "uri": "/get",
+            "upstream": {
+                "type": "roundrobin",
+                "nodes": {
+                    "127.0.0.1:8088": 1
+                }
             }
-            export admin_key=$(get_admin_key); echo $admin_key
-            cat conf/config.yaml
-            curl -v http://127.0.0.1:9180/apisix/admin/routes/1 \
-            -H "X-API-KEY: $admin_key" -X PUT -d '
-            {
-              "uri": "/get",
-              "upstream": {
-                  "type": "roundrobin",
-                  "nodes": {
-                      "127.0.0.1:8088": 1
-                  }
-              }
-            }'
-            result_code=`curl -I -m 10 -o /dev/null -s -w %{http_code} http://127.0.0.1:9080/get`
-            if [[ $result_code -ne 200 ]]; then
-                printf "result_code: %s\n" "$result_code"
-                echo "===============access.log==============="
-                cat logs/access.log
-                echo "===============error.log==============="
-                cat logs/error.log
-                exit 125
-            fi
+          }'
+          result_code=`curl -I -m 10 -o /dev/null -s -w %{http_code} http://127.0.0.1:9080/get`
+          if [[ $result_code -ne 200 ]]; then
+              printf "result_code: %s\n" "$result_code"
+              echo "===============access.log==============="
+              cat logs/access.log
+              echo "===============error.log==============="
+              cat logs/error.log
+              exit 125
+          fi
 
       - name: Check error log
         run: |
