add function to extract $admin_key

diff --git a/.github/workflows/source-install.yml b/.github/workflows/source-install.yml
--- a/.github/workflows/source-install.yml
+++ b/.github/workflows/source-install.yml
@@ -88,8 +88,13 @@ jobs:
 
       - name: Test apisix
         run: |
-          curl http://127.0.0.1:9180/apisix/admin/routes/1 \
-            -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
+            get_admin_key() {
+            local admin_key=$(grep "key:" -A3 conf/config.yaml | grep "key: *" | awk '{print $2}')
+            echo "$admin_key"
+            }
+            admin_key=$(get_admin_key)
+            curl http://127.0.0.1:9180/apisix/admin/routes/1 \
+            -H "X-API-KEY: $admin_key" -X PUT -d '
             {
               "uri": "/get",
               "upstream": {
@@ -99,15 +104,15 @@ jobs:
                   }
               }
             }'
-          result_code=`curl -I -m 10 -o /dev/null -s -w %{http_code} http://127.0.0.1:9080/get`
-          if [[ $result_code -ne 200 ]]; then
-              printf "result_code: %s\n" "$result_code"
-              echo "===============access.log==============="
-              cat logs/access.log
-              echo "===============error.log==============="
-              cat logs/error.log
-              exit 125
-          fi
+            result_code=`curl -I -m 10 -o /dev/null -s -w %{http_code} http://127.0.0.1:9080/get`
+            if [[ $result_code -ne 200 ]]; then
+                printf "result_code: %s\n" "$result_code"
+                echo "===============access.log==============="
+                cat logs/access.log
+                echo "===============error.log==============="
+                cat logs/error.log
+                exit 125
+            fi
 
       - name: Check error log
         run: |
